#!/bin/sh
### BEGIN INIT INFO
# Provides:          psilog-collector
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This script runs the psilog-collector service
### END INIT INFO

SCRIPT=/usr/bin/psilog-collector
RUNAS=root

PIDFILE=/var/run/psilog-collector.pid
LOGFILE=/var/log/psilog-collector.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'PsiLog-Collector already running' >&2
    return 1
  fi
  echo 'Starting PsiLog-Collector...'
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"

  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'PsiLog-Collector started'
  else
    echo "failed, see $LOGFILE" >&2
    return 1
  fi
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'PsiLog-Collector not running' >&2
    return 1
  fi
  echo 'Stopping PsiLog-Collector service...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'PsiLog-Collector stopped'
}

status() {
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
      echo 'PsiLog-Collector running'
    else
      echo 'PsiLog-Collector stopped'
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac